Resources:
  MealsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "mealId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "mealId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "Meals"
      GlobalSecondaryIndexes:
        - IndexName: "MealNameIndex"
          KeySchema:
            - AttributeName: "mealName"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"